### ISSUE TITLE
Relax databricks-cli version restriction

### ISSUE THREAD

**Issue by alexott** [crflynn/databricks-api#21]
Right now the package depends on the databricks-cli 0.12.x only, while the latest version is 0.14.3 - it would be useful to relax dependency version to avoid dependency on the old version

**Comment by crflynn** [comment]
I've been reluctant to upgrade because of [this issue](https://github.com/databricks/databricks-cli/issues/335). This is at least the second time that it's been removed from that code, and it still hasn't been fixed. Some folks [rely](https://github.com/crflynn/databricks-api/issues/6) on that functionality with this package so I'm hesitant to restrict to newer versions that don't have it.

I suppose that we could free the dependency either using `*` or using `<=` rather than `^` in dependency spec, but also add some warning to the user in docs about ensuring that they are pinning their version of `databricks-cli` as well. How does that sound?
